# Generated by Django 5.0.4 on 2024-04-07 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0003_alter_postoffice_options'),
        ('users', '0003_rename_mistake_in_customuser_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='worker', to='post_office.postoffice', verbose_name='в каком отделе работает сотрудник'),
        ),
    ]
