# Generated by Django 5.0.4 on 2024-06-03 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0003_alter_postoffice_options'),
        ('users', '0004_alter_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker', to='post_office.postoffice', verbose_name='в каком отделе работает сотрудник'),
        ),
    ]
