# Generated by Django 5.0.4 on 2024-04-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postoffice',
            name='index',
            field=models.IntegerField(blank=True, null=True, verbose_name='индекс почтового отделения'),
        ),
    ]
