# Generated by Django 5.0.4 on 2024-04-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0002_alter_postoffice_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postoffice',
            options={'verbose_name': 'Почтовое отделение/отдел', 'verbose_name_plural': 'Почтовые отделения/отделы'},
        ),
    ]
