# Generated by Django 5.0.4 on 2024-04-07 09:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post_office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='ценна')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='производитель')),
                ('inventory_number', models.BigIntegerField(unique=True, verbose_name='инвертарный номер')),
                ('serial_number', models.BigIntegerField(unique=True, verbose_name='серийный номер')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего редактирования')),
                ('photo', models.ImageField(upload_to='images/normal_photos/%Y/%m/%d', verbose_name='Фото')),
                ('movement_history', models.TextField(blank=True, max_length=200, verbose_name='история премещения')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='post_office.postoffice', verbose_name='какому опс/отделу пренадлежит')),
            ],
        ),
    ]
