# Generated by Django 5.0.4 on 2024-04-07 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_options_and_more'),
        ('post_office', '0003_alter_postoffice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementhistory',
            name='from_where',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_where_equipment', to='post_office.postoffice', verbose_name='с откуда техника'),
        ),
        migrations.AlterField(
            model_name='movementhistory',
            name='where',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_is_now', to='post_office.postoffice', verbose_name='куда техника'),
        ),
    ]
