# Generated by Django 5.0.4 on 2024-04-08 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_movementhistory_from_where_and_more'),
        ('post_office', '0003_alter_postoffice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(blank=True, choices=[(None, 'Статус техники'), ('a', 'В наличии'), ('b', 'отправленна'), ('c', 'потерянна')], max_length=1, verbose_name='Статус техники'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='post_office.postoffice', verbose_name='какому опс/отделу пренадлежит'),
        ),
    ]
