# Generated by Django 5.0.4 on 2024-04-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipment_status_alter_equipment_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movementhistory',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='photo',
            field=models.ImageField(upload_to='static/images/normal_photos/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[(None, 'Статус техники'), ('a', 'В наличии'), ('b', 'отправленна'), ('c', 'потерянна')], max_length=1, verbose_name='Статус техники'),
        ),
    ]
