# Generated by Django 5.0.4 on 2024-04-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_movementhistory_options_alter_equipment_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='bar_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Штрих номер'),
        ),
    ]
