# Generated by Django 5.0.4 on 2024-04-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_equipment_bar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='bar_number',
            field=models.CharField(default=4, max_length=20, unique=True, verbose_name='Штрих номер'),
            preserve_default=False,
        ),
    ]
