# Generated by Django 5.0.4 on 2024-06-08 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_alter_movementhistory_from_where_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='bar_number',
            field=models.CharField(editable=False, max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(12)], verbose_name='Штрих номер'),
        ),
    ]
